
CREATE TABLE IF NOT EXISTS REGEMPLOYEE
(	Fname		VARCHAR(15)			NOT NULL,
    Lname		VARCHAR(15)			NOT NULL,
    Ssn			CHAR(9)				NOT NULL,
	Phone		VARCHAR(12)			NOT NULL,
    Address		VARCHAR(30)			NOT NULL,
    Email		VARCHAR(25)			NOT NULL,
    Salary		DECIMAL(10,2)		NOT NULL,
	Username	VARCHAR(25)			NOT NULL,
	Password	VARCHAR(25)			NOT NULL,
    PRIMARY KEY (Ssn),
	UNIQUE(Username));

CREATE TABLE IF NOT EXISTS TEACHER
(	Fname		VARCHAR(15)			NOT NULL,
    Lname		VARCHAR(15)			NOT NULL,
    Ssn			CHAR(9)				NOT NULL,
    Gender		CHAR(10)			NOT NULL,
    Bdate		DATE				NOT NULL,
	Phone		VARCHAR(12)			NOT NULL,
    Address		VARCHAR(30)			NOT NULL,
    Email		VARCHAR(25)			NOT NULL,
    Salary		DECIMAL(10,2)		NOT NULL,
	Username	VARCHAR(25)			NOT NULL,
	Password	VARCHAR(25)			NOT NULL,
	courseID	CHAR(5),
    PRIMARY KEY (Ssn),
    FOREIGN KEY (courseID) REFERENCES CLASS(courseID),
	UNIQUE(Username));
    
CREATE TABLE IF NOT EXISTS CLASS
(	courseID	CHAR(5)		NOT NULL,
	courseName	VARCHAR(30) NOT NULL,
	studentID	CHAR(7),
    participation CHAR,
    PRIMARY KEY (courseID),
    FOREIGN KEY (studentID) REFERENCES STUDENT(studentID));

CREATE TABLE IF NOT EXISTS STUDENT
(	studentID	CHAR(7)				NOT NULL,
	Fname		VARCHAR(15)			NOT NULL,
	MInit		CHAR,
    Lname		VARCHAR(15)			NOT NULL,
    Gender		CHAR(10)			NOT NULL,
    Bdate		DATE				NOT NULL,
	parentPhone	VARCHAR(12)			NOT NULL,
    Address		VARCHAR(30)			NOT NULL,
    Email		VARCHAR(25)			NOT NULL,
	Username	VARCHAR(25)			NOT NULL,
	Password	VARCHAR(25)			NOT NULL,
    PRIMARY KEY (studentID),
    UNIQUE(Username));

CREATE TABLE IF NOT EXISTS PARENT
(	Fname		VARCHAR(15)			NOT NULL,
    Lname		VARCHAR(15)			NOT NULL,
	Phone		VARCHAR(12)			NOT NULL,
    Address		VARCHAR(30)			NOT NULL,
    Email		VARCHAR(25)			NOT NULL,
	studentID	CHAR(7),
    PRIMARY KEY (Phone),
    FOREIGN KEY (studentID) REFERENCES STUDENT(studentID));

CREATE TABLE IF NOT EXISTS SYSTEMADMIN
(	ID	CHAR(7)		NOT NULL,
	Fname		VARCHAR(15)			NOT NULL,
    Lname		VARCHAR(15)			NOT NULL,
	Username	VARCHAR(25)			NOT NULL,
	Password	VARCHAR(25)			NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE(Username));

CREATE TABLE IF NOT EXISTS SCHOOLDEPT
(	schoolID	CHAR(10)		NOT NULL,
	courseID	CHAR(5),
	Ssn			CHAR(9),
	ID			CHAR(7),
	Essn		CHAR(9),
    PRIMARY KEY (schoolID),
    FOREIGN KEY (courseID) REFERENCES CLASS(courseID),
	FOREIGN KEY (Ssn) REFERENCES TEACHER(Ssn),
    FOREIGN KEY (ID) REFERENCES SYSTEMADMIN(ID),
	FOREIGN KEY (Essn) REFERENCES REGEMPLOYEE(Ssn));

CREATE TABLE IF NOT EXISTS GRADES
(	courseG		CHAR		NOT NULL,
	courseID    CHAR(5),
	studentID 	CHAR(7),
	FOREIGN KEY (courseID) REFERENCES CLASS(courseID),
    FOREIGN KEY (studentID) REFERENCES STUDENT(studentID));

CREATE TABLE IF NOT EXISTS ATTENDANCE
(	attDate		DATE		NOT NULL,
	studentID	CHAR(7),
    FOREIGN KEY (studentID) REFERENCES STUDENT(studentID));

CREATE TABLE IF NOT EXISTS VIOLATIONS
(	vioDate		DATE		NOT NULL,
	vioType		VARCHAR(20)	NOT NULL,
	studentID	CHAR(7),
    FOREIGN KEY (studentID) REFERENCES STUDENT(studentID));